import type { Theme } from "@/types";

export const githubLight: Theme = {
  id: "github-light",
  name: "GitHub Light",
  author: "GitHub",
  isDark: false,
  terminal: {
    background: "#ffffff",
    foreground: "#24292f",
    cursor: "#24292f",
    cursorAccent: "#ffffff",
    selectionBackground: "#b6e3ff",
    ansi: {
      black: "#24292f",
      red: "#cf222e",
      green: "#116329",
      yellow: "#4d2d00",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#1b7c83",
      white: "#6e7781",
      brightBlack: "#57606a",
      brightRed: "#a40e26",
      brightGreen: "#1a7f37",
      brightYellow: "#633c01",
      brightBlue: "#218bff",
      brightMagenta: "#a475f9",
      brightCyan: "#3192aa",
      brightWhite: "#8c959f",
    },
  },
  ui: {
    bgBase: "#ffffff",
    bgSurface: "#f6f8fa",
    bgElevated: "#ffffff",
    bgOverlay: "#ffffff",
    bgHover: "#f3f4f6",
    bgActive: "#eaeef2",

    borderSubtle: "#eaecef",
    borderDefault: "#d0d7de",
    borderStrong: "#afb8c1",

    textPrimary: "#24292f",
    textSecondary: "#57606a",
    textMuted: "#6e7781",
    textInverted: "#ffffff",

    accent: "#0969da",
    accentHover: "#0860c7",
    accentMuted: "#b6d4fe",
    accentContrast: "#ffffff",
    success: "#1a7f37",
    warning: "#9a6700",
    danger: "#cf222e",
    info: "#0969da",

    titlebarBg: "#f6f8fa",
    titlebarFg: "#24292f",
    tabActiveBg: "#ffffff",
    tabInactiveBg: "#f6f8fa",
    tabHoverBg: "#f0f3f6",
    tabBorder: "#d0d7de",
  },
};
